### ISSUE TITLE
Can cloudtik support Alicloud?

### ISSUE THREAD

**Issue by george-gu-2021** [oap-project/cloudtik#1194]
Can cloudtik support Alicloud? There is no Alicloud ECS support per the readme. Thanks!

**Comment by jerrychenhf** [comment]
@george-gu-2021 Hi George,
Alibaba Cloud support is currently 98% completion.  We will get it ready for anyone to use Alibaba Cloud in 1 or 2 days.

I will give you a notification when it is done soon.

Thanks,
Haifeng

**Comment by george-gu-2021** [comment]
@jerrychenhf , thanks for the timely feedback!  We look forward to watching the live demo!
